cout<<"Ma tran ke:"<<endl;
    // maTranKe=randGraph(6, 0.2, cohuong);
    // inMaTran(maTranKe);
    // cout<<"Danh sach canh:"<<endl;
    // danhSachCanh1=danhSachCanh(maTranKe,cohuong);
    // inDanhSachCanh(danhSachCanh1);
    // cout<<"Ma tran lien thuoc:"<<endl;
    // maTranLienThuoc1=maTranLienThuoc(maTranKe,cohuong);
    // inMaTran(maTranLienThuoc1);
    // chuyenMaTran1=chuyenMaTran(maTranKe);
    // cout<<"Danh sach ke:"<<endl;
    // danhSachKe1=danhSachKe(chuyenMaTran1);
    // inDanhSachKe(danhSachKe1);